version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_CONNECTION_STRING=Server=db;Database=my_database;User=sa;Password=your_password

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=your_password
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:
